const products = [
  {
    _id: '1',
    name: 'Black Body Con',
    image: '/images/partywear.png',
    description:
      'Black Body Con Party Wear is in good condition and has been worn once by its previous owner ',
    brand: 'FabIndia',
    category: 'Party Wear',
    price: 3999.99,
    countInStock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Summer Wear One-Piece',
    image: '/images/summerWearr.png',
    description:
      'Summer Wear is in best condition and has been worn by former Miss Nepal in a promotion event',
    brand: 'Urban Girl',
    category: 'Summer Wear',
    price: 999.99,
    countInStock: 1,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Maroon One-Piece',
    image: '/images/maroondresss.png',
    description: 'Maroon One-Piece is in good condition.',
    brand: 'Unknown',
    category: 'One-piece',
    price: 929.99,
    countInStock: 1,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Pink One-piece',
    image: '/images/pinkdresss.png',
    description:
      'Pink One-piece has never been worn by its previous owner and is brand new',
    brand: 'Unknown ',
    category: 'One-piece',
    price: 1999.99,
    countInStock: 1,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Blue Prom Dress',
    image: '/images/promdresss.png',
    description: 'Blue Prom Dress is in its best condition',
    brand: 'Boutique Item',
    category: 'Prom Dress',
    price: 10000,
    countInStock: 1,
    rating: 5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Light Green Spring Wear',
    image: '/images/springwearr.png',
    description: 'Spring Wear is in good condition',
    brand: 'Unknown',
    category: 'One-piece',
    price: 999.99,
    countInStock: 1,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: '7',
    name: 'Red One-Piece',
    image: '/images/reddresss.png',
    description: 'Red Dress is in good condition',
    brand: 'Juniper',
    category: 'Gown',
    price: 2099.99,
    countInStock: 1,
    rating: 4.5,
    numReviews: 14,
  },
  {
    _id: '8',
    name: 'Yellow One-piece',
    image: '/images/yellowdresss.png',
    description: 'Yellow One-piece is in good condition',
    brand: 'Fashion Australia',
    category: 'Casual Wear',
    price: 1999.99,
    countInStock: 1,
    rating: 4.5,
    numReviews: 6,
  }
]

export default products
